ch_cookie_consent:
    theme: 'light' # light, dark
    categories: ['analytics']
    use_logger: false # Logs user actions to database
    position: 'bottom' # top, bottom
    simplified: false # When set to true the user can only deny or accept all cookies at once
    http_only: true # Sets HttpOnly on cookies
