vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: public/images/articles/
            upload_destination: '%kernel.project_dir%/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
