vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: '%app.path.article_images%'
            upload_destination: '%kernel.project_dir%/%app.path.article_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true